var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:9545"));

// edit post compile contract 'interface' whenever update .sol
var abi = JSON.parse('[{"constant":false,"inputs":[{"name":"_unique_id","type":"bytes32"},{"name":"_create_op","type":"bytes32"},{"name":"_asset_type","type":"bytes32"},{"name":"_txee_id","type":"bytes32"}],"name":"addPlantAsset","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"AYT","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_unique_id","type":"bytes32"},{"name":"_create_op","type":"bytes32"},{"name":"_asset_type","type":"bytes32"},{"name":"_txee_id","type":"bytes32"}],"name":"addPackageAsset","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"x","type":"bytes32"}],"name":"bytes32ToString","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"v","type":"uint256"}],"name":"uintToBytes","outputs":[{"name":"ret","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"assetInfo","type":"string"}],"name":"AddPlantAssetEvent","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"assetInfo","type":"string"}],"name":"ModifyPlantAssetStateEvent","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"assetInfo","type":"string"}],"name":"AddPackageAssetEvent","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"assetInfo","type":"string"}],"name":"ModifyPackageAssetStateEvent","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"s","type":"string"}],"name":"TestOutputStringEvent","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"x","type":"bytes32"}],"name":"TestOutputBytes32Event","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"x","type":"int256"}],"name":"TestOutputIntEvent","type":"event"}]');

//console.log(abi);

MITSContract = web3.eth.contract(abi);

// In your nodejs console, execute contractInstance.address to get the address at which the contract is deployed and change the line below to use your deployed address
var contractInstance = MITSContract.at('0x345ca3e014aaf5dca488057592ee47305d9b3e10');
